---
title: "Discussion-11"
author: "Ahsanul Choudhury"
date: "November 9, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

My choice for this week's discussion is expedia recommender system:

https://www.expedia.com/
   
1. Scenario Design Analysis  


     a)Who are your target users?
    
     -Travelers looking to plan and book travels. 
    
    
     
     b)What are their key goals?
    
     -The key goals of the site users is to research and book hotels, flights, rent cars and plan activities during their travel.
    
     
     
     c)How can you help them accomplish those goals?
    
     -Expedia provides a one stop shop for travelers to look for hotels, flight and car tentals and book in advance through their website, it also provides a "things to do" section where users can plan their activities during traveling. Expedia provides recommendations based on users past activities and activities of similar users.
    
* * *

2. Reverse Engineering
    
    
    -Expedia uses available user information, user's past clicking and booking behaviour, destination and matches them with hotel characteristics to provide recomendations. Expedia has a feature called "scratch pad", where user can save their searches, the prices on saved scratch pad searches are always updated and can be emailed tho user's if there is a change that might interest the user. Expedia uses this search history in their recomendation.
    
* * *    

3. Recommendations for Improvement

    
    -Knowing the user better can be key to create an effective recommender system, expedia can include the option to create a user profile with basic customer information which may include their interest, life style, hobby, profession and other basic informaton. This information can than be used to create recommendation based on activity of other user with similar user profile.